config/routes.rb
Rails.application.routes.draw do
  root to: 'user#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/user/:user_id/post', to: 'post#index', as: 'index_posts'
  get '/user/:user_id/post/:post_id', to: 'post#show', as: 'show_posts'
  get '/post/new', to: 'post#new',as: 'add_post'
  get '/user/:user_id/post/:user_id/comments/new', to: 'comments#new', as: 'new_comment'
  post '/user/:user_id/post/:user_id/comments', to: 'comments#create', as: 'create_comment'
  post '/user/:user_id/post/:user_id/likes', to: 'likes#create', as: 'create_like'
  post '/post', to: 'post#create', as: 'create_post'

  resources :user,only: [:show] do 
    resources :post, only: [:index, :show]
  end

  resources :post, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  belongs_to :post, foreign_key: 'post_id', class_name: 'Post'
  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  belongs_to :post, foreign_key: 'post_id', class_name: 'Post'
  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  after_create :update_posts_counter

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :posts, foreign_key: :author_id
  validates_presence_of :name
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  def latest_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user = User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user
    if @comment.save!
      redirect_to post_show_path(current_user)
    else
      flash.now[:alert] = 'Comment creation failed'
    end
  end

  def comment_params
    params.require(:comment).permit(:post_id, :text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(like_params)
    @like.author_id = current_user

    if @like.save
      redirect_to post_show_path(current_user)
    else
      flash.now[:alert] = 'Like creation failed'
    end
  end

  private

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello; end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user
    flash.now[:notice] = 'Comment created successfully' if @post.save!
    redirect_to user_path(current_user)
  end

  def show
    @post = Post.includes(:author).find(params[:post_id])
    @user = User.find(params[:user_id])
    @comments = Comment.includes(:post).all
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/new.html.erb
<div>
  <h2>Create a new comment</h2>
  <%= form_with url: create_comment_path, model: Comment do |form| %>
  <%= form.hidden_field :post_id, value: @post_id %>
  <%= form.text_area :text, placeholder: 'Insert your Text here' %><br>
  <%= form.submit "Add new comment" %>
  <% end %>
  <div>
   <%= link_to "<button>Go Back</button>".html_safe, index_posts_path, :class => 'seeAllpostsButton' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<%= form_with url: create_like_path, model: Like do |form| %>
  <%= form.hidden_field :post_id, value: @post_id %>
  <div'>
    <%= form.submit "Like post" %>
  </div>
<% end %>

app/views/pages/hello.html.erb
<h1>Pages#hello</h1>
<p>Find me in app/views/pages/hello.html.erb</p>

app/views/post/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>"Blog Website"</title>
    <%= stylesheet_link_tag 'post/index', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  
  <div class="subParentContent">
  <div class="contentIconName"> 
    <div class="contentIcon">
      <img src=<%= @user.photo %> alt:"User Display Image" class="contentIcon" />
    </div> 
    <div class="contentNamePost">
      <h2 class="name">
        <%= @user.name %>
      </h2>
      <h3 class="numberPosts">
        Number of posts: <%= @user.posts_counter %>
      </h3> 
    </div> 
  </div>
  <ul id="posts_li">
    <% @user.posts.each_with_index do |post, index| %>
    <li id="p_item"> 
        <div class="postSection">  <h2 class="numPost">Post <%= index + 1 %> </h2>
          <p class="textPost">
            <%= post.text %>
          </p>
          <h3 class="comLikesPost">
            Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %>
          </h3>
        </div>
        <div class="commentSection">
          <% @user.comments.each_with_index do |comment, index| %>
          <% if comment.author_id == post.id %>
          <div class="commentByUser">
            <h2 class="userComment">Comment <%= index + 1 %>
              <h3 class="commentMessage"><%= comment.text %> </h3>
            </h2>
          </div>
          <% end %>
          <% end %>
        </div>
        <%= form_with url: create_like_path, model: Like do |form| %>
        <%= form.hidden_field :post_id, value: @post_id %>
        <div>
          <%= form.submit "Like post" %>
        </div>
        <% end %>
        <%= link_to "<button>Add Comment</button>".html_safe, new_comment_url(@user), :class => 'seeAllpostsButton' %>
    </li>
    <% end %>
  </ul>
  </div>
  </div>
  </div>
  </body>
</html>

app/views/post/new.html.erb
<%= form_with url: post_index_path, model: Post do |form| %>
  <%= form.label :title, 'Add a title for your post: ' %><br>
  <%= form.text_field :title, placeholder: 'Title:' %> <br>
  <%= form.label :text, 'Add text to your post:' %><br>
  <%= form.text_area :text, placeholder: 'Text' %><br>
  <%= form.submit "Create Post"%>
<% end %>

app/views/post/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>"Mi sitio web"</title>
    <%= stylesheet_link_tag 'post/show', media: 'all', 'data-turbolinks-track':
    'reload' %>
  </head>
  <body>
    <div class="postComment">
      <div class="postSection">
        <h1 class="numPost">Post <%= @post.id %> by <%= @post.author.name %></h1>
        <h2 class="numPost">Title: <%= @post.title %></h2>
        <h3 class="comLikesPost">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></h3>
        <p class="textPost">
          <%= @post.text %>
        </p>
      </div>
      <div class="commentSection">
        <% @comments.each_with_index do |comment, index| %>
        <% if comment.author_id == @post.id %>
        <div class="commentByUser">
          <h2 class="userComment">
            Comment <%= index + 1 %>
            <h3 class="commentMessage"><%= comment.text %></h3>
          </h2>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/user/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>"Blog Website"</title>
    <%= stylesheet_link_tag "user/index",
    media: "all",
    "data-turbolinks-track": "reload" %>
  </head>
  <body>

    <div class="subParentContent">
       <% @users.each do |user| %>
       <%= link_to user_path(user), :class => 'contentIconName' do %>
      <div class="contentIconName">
        <div class="contentIcon">
          <img src=<%= user.photo %> alt:"User Display Image" class="contentIcon" />
        </div>
        <div class="contentNamePost">
          <h2 class="name"><%= user.name %></h2>
          <h3 class="numberPosts">Number of posts: <%= user.posts_counter %></h3>
        </div>
      </div>
       <% end %>
       <% end %>
    </div>
  </body>
</html>

app/views/user/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>"Blog Website"</title>
  <%= stylesheet_link_tag 'user/show' , media: 'all' , 'data-turbolinks-track' => 'reload' %>
</head>

<body>

  <div class="subParentContent">
    <% @user.tap do |user| %>
    <div class="contentIconName">
      <div class="contentIcon">
        <img src=<%= user.photo %> alt:"User Display Image" class="contentIcon" />
      </div>
      <div class="contentNamePost">
        <h2 class="name"><%= user.name %></h2>
        <h3 class="numberPosts">Number of posts: <%= user.posts_counter %></h3>
      </div>
    </div>
    <div class="bio">
      <p class="InBio"> Bio <br><br>
        <%= user.bio %>
      </p>

    </div>
    <% end %>

    <ul id="posts_li">
      <% @user.latest_posts.each_with_index do |post, index| %>
      <li id="p_item">
        <h2 class="numPost">Post <%= (index + 1) %></h2>
        <p class="textPost">
          <%= post.text %>
        </p>
        <h3 class="comLikesPost">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %> </h3>
      </li>
      <% end %>
    </ul>
    <%= link_to "<button>Add Post</button>".html_safe, add_post_path, :class => 'seeAllpostsButton' %>
    <%= link_to "<button>See All Posts</button>".html_safe, index_posts_url(:user_id => @user.id), :class => 'seeAllpostsButton' %>
    <button>Pagination</button>
  </div>
  </div>
</body>
</html>